#ifndef QQMODELSLOG_H
#define QQMODELSLOG_H

#include <QDebug>

#define QMODELSLOG_LEVEL_TRACE 0
#define QMODELSLOG_LEVEL_DEBUG 1
#define QMODELSLOG_LEVEL_INFO 2
#define QMODELSLOG_LEVEL_WARNING 3
#define QMODELSLOG_LEVEL_CRITICAL 4

#define QMODELSLOG_MIN_LEVEL QMODELSLOG_LEVEL_INFO

#if (QMODELSLOG_MIN_LEVEL<=QMODELSLOG_LEVEL_TRACE)
#define QMODELSLOG_TRACE QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1BQMODELS").debug
#else
#define QMODELSLOG_TRACE QMessageLogger().noDebug
#endif
#if (QMODELSLOG_MIN_LEVEL<=QMODELSLOG_LEVEL_DEBUG)
#define QMODELSLOG_DEBUG QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"QMODELS").debug
#else
#define QMODELSLOG_DEBUG QMessageLogger().noDebug
#endif
#if (QMODELSLOG_MIN_LEVEL<=QMODELSLOG_LEVEL_INFO)
#define QMODELSLOG_INFO QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"QMODELS").info
#else
#define QMODELSLOG_INFO QMessageLogger().noDebug
#endif
#if (QMODELSLOG_MIN_LEVEL<=QMODELSLOG_LEVEL_WARNING)
#define QMODELSLOG_WARNING QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"QMODELS").warning
#else
#define QMODELSLOG_WARNING QMessageLogger().noDebug
#endif
#if (QMODELSLOG_MIN_LEVEL<=QMODELSLOG_LEVEL_CRITICAL)
#define QMODELSLOG_CRITICAL QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"QMODELS").critical
#else
#define QMODELSLOG_CRITICAL QMessageLogger().noDebug
#endif
#define QMODELSLOG_FATAL QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"QMODELS").fatal

#endif // QQMODELSLOG_H
